include $(GNUSTEP_MAKEFILES)/common.make
APP_NAME = cal
cal_OBJC_FILES = src/main.m
cal_HEADERS = src/main.h
cal_RESOURCE_FILES = cal.plist window.gorm
//cal_MAIN_MODEL_FILE = window.gorm
include $(GNUSTEP_MAKEFILES)/application.make

